qute: linux needs a new bottle (glibc broken on linux)
In TravisCI build https://travis-ci.org/touist/homebrew-touist/jobs/407677741:

Testing qute
==> /home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute /tmp/qute-test-20180724-10419-1kta43j/test.dimacs
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_program_options-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_program_options-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_thread-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_log-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_log-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_system-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_chrono-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_date_time-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_log_setup-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_log_setup-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_filesystem-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_filesystem-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_filesystem-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_regex-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_regex-mt.so.1.67.0)
/home/linuxbrew/.linuxbrew/Cellar/qute/0.0.1_3/bin/qute: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/libboost_regex-mt.so.1.67.0)
Error: qute: failed
<10> expected but was
<1>.