rareqs: linux needs a new bottle (glibc broken on linux)
Error in https://travis-ci.org/touist/homebrew-touist/jobs/407677741:

Testing rareqs
==> /home/linuxbrew/.linuxbrew/Cellar/rareqs/1.1_1/bin/rareqs /tmp/rareqs-test-20180724-10453-iz6f8r/test.dimacs
/home/linuxbrew/.linuxbrew/Cellar/rareqs/1.1_1/bin/rareqs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/linuxbrew/.linuxbrew/Cellar/rareqs/1.1_1/bin/rareqs)
/home/linuxbrew/.linuxbrew/Cellar/rareqs/1.1_1/bin/rareqs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/Cellar/rareqs/1.1_1/bin/rareqs)
Error: rareqs: failed
<10> expected but was
<1>.