travis: among others, fix old openssl ('tlsv1 alert') (#17)
Changes:
- separate the two ruby contexts:
  1) ruby 2.3 (for brew) is used by default (rvm use system)
  2) ruby 'default' (for aws-s3 and gem install) is used using
     'rvm default do ...'
- install gmp, openssl, openssl@1.1 and libyaml so that
  the ruby default (rvm default do...) works again
- instead of 'brew update', reinstall brew from scratch as it takes
  much less time and avoid stupid errors with linking and python@2
- update macos images
- do not reinstall xquartz each time, only if it is outdated (it takes
  ~2 minutes to reinstall xquartz otherwise)

Using 'rvm default' (and not rvm system) fixes the error:

    # sudo gem install aws-sdk-s3

    ERROR:  Could not find a valid gem 'aws-sdk-s3' (>= 0), here is why:
    Unable to download data from https://rubygems.org/ - SSL_connect returned=1
    errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
    (https://rubygems.org/latest_specs.4.8.gz)
    The command "sudo gem install aws-sdk-s3" failed and exited with 2.